logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.fondofit: INFO
    com.fondofit.stock.portfolio.proxy: DEBUG

spring:
  profiles:
    active: local
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  application: 
    name: stock-portfolio-service
server:
  port: 9001
management: 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#  health:
#    status:
#      http-mapping:
#          DOWN: 503
#          UP: 200  


          

