spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/stock-db
stock:
  exchange:
    url: http://localhost:9000
#resilience4j.circuitbreaker:
#  instances:
#    stock-exchange:
#      registerHealthIndicator: true
#      ringBufferSizeInClosedState: 5
#      ringBufferSizeInHalfOpenState: 3
#      waitDurationInOpenState: 10s
#      failureRateThreshold: 50
#      recordExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#        - java.io.IOException
#        - java.util.concurrent.TimeoutException
#        - org.springframework.web.client.ResourceAccessException
#      ignoreExceptions:
#          - com.gl.orderManagementApp.service.MyException
#    service2:
#      registerHealthIndicator: true
#      ringBufferSizeInClosedState: 6
#      ringBufferSizeInHalfOpenState: 4
#      waitDurationInOpenState: 20s
#      failureRateThreshold: 60
